<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="<?=$this->baseUrl()?>/js/jquery-1.3.2.min.js" type="text/javascript"></script>

<script language="javascript"> 
function validar() {

nombre= document.form8.nombre.value;
apellido= document.form8.apellido.value;
direccion = document.form8.direccion.value;
telefono = document.form8.tel.value;
email = document.form8.email.value;
email2 = document.form8.email2.value;

ciudad = document.form8.ciudad.value;
estado = document.form8.estado.value;
pais = document.form8.pais.value;
password= document.form8.password.value;
password1= document.form8.password1.value;


	if( nombre == null || nombre.length == 0 || /^\s+$/.test(nombre) ) {
		alert('[ERROR] Nombre no puede esta vacio');
	 return false;
	}

	else if(apellido== null || apellido.length == 0 || /^\s+$/.test(apellido) ) {
		alert('[ERROR] Apellido  Seleccione no puede estar vacio');
		 return false;
		}
	
	else if( direccion  == null || direccion.length == 0 || /^\s+$/.test(direccion) ) {
		alert('[ERROR] Direccion  Seleccione no puede estar vacio');
		 return false;
		}

	else if (isNaN(telefono)|| telefono == null || telefono.length == 0 || /^\s+$/.test(telefono) ) {
	      // Si no se cumple la condicion...
	      alert('[ERROR] Telefono Solo numero no puede estar vacio');
	      return false;
	      }

	else if (email == null || email.length == 0 || /^\s+$/.test(email)){
	      // Si no se cumple la condicion...
	      alert('[ERROR] Email no puede estar vacio');
	      return false;
	      }


	
		else if( ciudad  == null || ciudad.length == 0 || /^\s+$/.test(ciudad) ) {
		alert('[ERROR]ciudad  Seleccione No puede estar vacio');
		 return false;
		}

	else if( estado  == null || estado.length == 0 || /^\s+$/.test(estado) ) {
		alert('[ERROR] Estado  Seleccione no puede estar vacio');
		 return false;
		}

	else if( pais == null || pais.length == 0 || /^\s+$/.test(pais) ) {
		alert('[ERROR] Pais no puede estar vacio');
		 return false;
		}

	
	else if(password== null ||password.length == 0 || /^\s+$/.test(password)) {
		alert('[ERROR] Password no puede esta vacio primera casilla');
		 return false;
		}

	if(password != password1){
		   alert('[ERROR] Password o clave no son iguales');
			 return false;
		   }

	elemento = document.getElementById("terminos");
	if( !elemento.checked ) {
		 alert('[ERROR] Aceptar Terminos y condiciones');
	  return false;
	}

	if(email != email2){
		   alert('[ERROR] Email no son iguales');
			 return false;
		   }

	

	
	

  return true;




  
}
</script>

<script language="javascript" type="text/javascript">
function ciudadremi(idciu,ciu1,estado1,pais1){
	document.getElementById('idDTcity').value = idciu;
	document.getElementById('DTcity').value = ciu1;
	document.getElementById('DTregion').value = estado1;
    document.getElementById('DTcountry').value = pais1;
    
	//location.reload();
}
</script>



<script type="text/javascript">
$(document).ready(function(){
	cargar_paises();
	$("#pais").change(function(){dependencia_estado();});
	$("#estado").change(function(){dependencia_ciudad();});
	
	$("#estado").attr("disabled",true);
	$("#ciudad").attr("disabled",true);
	
});

function cargar_paises()
{
	$.get("<?=$this->baseUrl()?>/web/webfunciones/listapaisesweb", function(resultado){
		if(resultado == false)
		{
			alert("Seleccione pais");
		}
		else
		{
			$('#pais').append(resultado);			
		}
	});	
}
function dependencia_estado()
{
	var code = $("#pais").val();
	$.get("<?=$this->baseUrl()?>/web/webfunciones/cargarestadosweb", { code: code },
		function(resultado)
		{
			if(resultado == false)
			{
				alert("Seleccione Estado");
			}
			else
			{
				$("#estado").attr("disabled",false);
				document.getElementById("estado").options.length=1;
				$('#estado').append(resultado);			
			}
		}

	);
}

function dependencia_ciudad()
{
	var code = $("#estado").val();
	$.get("<?=$this->baseUrl()?>/web/webfunciones/cargarciudades", { code: code },
	  function(resultado){
		if(resultado == false)
		{
			alert("Cargar Ciudad");
		}
		else
		{
			$("#ciudad").attr("disabled",false);
			document.getElementById("ciudad").options.length=1;
			$('#ciudad').append(resultado);			
		}
	});	
}





	
</script>



<div id="ja-containerwrap-f">
<div id="ja-container">
<div id="ja-container2" class="clearfix">
<div id="ja-mainbody" class="clearfix">
<div id="ja-content" class="clearfix">
<div id="ja-current-content" class="clearfix">



<!-- coloque aqui solo lo de la mitad -->
<div class="contentpane">

	
	
<!--<div style="width:100%;" align="center">
    <img alt="" src="/webmodule/img/paso1.gif">
</div>
-->
     
           
	
	
	
<br>
<div style="width:100%;">
<div id="" style="width:100%;">
   <form class="forms" name="form8" id="signupForm" onSubmit="return validar()" method="post" action="<?=$this->baseUrl()?>/web/webindex/registrocas"> 
   <?php if($this->error):?><table>
   <tr>
   <td width="300"></td>
   <td style="font-size:16px; color:#F00"><?php echo"Los campos con * son requeridos ".$this->error;?></td>
   <td></td>
   </tr>
   </table>
   <?php endif;?>
    <table id="" class="ColorTable" cellpadding="3" cellspacing="3" align="center">
	<tbody>
	<!--  
	<tr>
		<td class="CampoLabels">
                <span id="">Agencia</span>
          </td>
		<td class="CampoTextBox">
                <select name="agencia" size="1" id="select"> 
                  <?php //foreach ($this->agencia as $agen):?>
                 <option value="<?php //echo$agen->getid();?>"><?php //echo$agen->getname()?></option>
                <?php //endforeach;?>
            </select><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
              
          </td>
	</tr>
	-->
	<tr>
	<input type="hidden" name="agencia" value="<?php if(sizeof($this->session1)>0){echo$this->session1->agencia;}else{if($_GET['ag']){echo$_GET['ag'];}else{echo"1";}}?>" >
		<td class="CampoLabels">
                <span id="">Nombres</span>
          </td>
		<td class="CampoTextBox">
                <input name="nombre" maxlength="100" id="" style="width:250px;" type="text" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->nombre;}?>"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
                
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">Apellidos</span>
          </td>
		<td class="CampoTextBox">
                <input name="apellido" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->apellido;}?>" maxlength="100" id="" style="width:250px;" type="text"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
              
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">Documento de Identidad</span>
          </td>
		<td class="CampoTextBox">
                <input name="cc" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->cc;}?>" maxlength="20" id="ctl00_ContentPlaceHolder1_ctlNewCliente1_txtCedula" style="width:150px;" type="text"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
                
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">Telefono Contacto</span></td>
		<td class="CampoTextBox">
                <input name="tel" maxlength="20" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->tel;}?>" id="" style="width:150px;" type="text"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
                
          </td>
	</tr>
    <tr>
		<td class="CampoLabels">
                <span id="">Movil Contacto</span>
          </td>
		<td class="CampoTextBox">
                <input name="movil" maxlength="20" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->movil;}?>" id="" style="width:150px;" type="text"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
             
          </td>
	</tr>
    <tr>
		<td class="CampoLabels">
                <span id="">Telefono Oficina</span></td>
		<td class="CampoTextBox">

                <input name="telofi" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->telofi;}?>" maxlength="20" id="" style="width:150px;" type="text">
          </td>
		<td class="CampoErrores" width="20px">
                <span id="" style="color:Red;visibility:hidden;">*</span>
          </td>
	</tr>
    <tr>
		<td class="CampoLabels">
                <span id="ctl00_ContentPlaceHolder1_ctlNewCliente1_Label19">Direccion</span>
          </td>
		<td class="CampoTextBox">
                <input name="direccion" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->direccion;}?>" maxlength="150" id="" style="width:400px;" type="text">
          </td>
		<td class="CampoErrores" width="20px">
                <span id="" style="color:Red;">*</span>
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">E-mail</span>
          </td>
		<td class="CampoTextBox">
                <input name="email" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->email;}?>" style="width:400px;" type="text">
          </td>
		<td class="CampoErrores" width="20px"><span id="" style="color:Red;">*</span>
     
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">Verificar E-mail</span>
          </td>
		<td class="CampoTextBox">
                <input name="email2" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->email;}?>" style="width:400px;" type="text">
          </td>
		<td class="CampoErrores" width="20px"><span id="" style="color:Red;">*</span>
     
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="">Zip (opcional)</span>
          </td>
		<td class="CampoTextBox">
                <input name="zip" maxlength="150" value="<?php if(sizeof($this->session1) > 0){ echo $this->session1->zip;}?>" id="" style="width:150px;" type="text">
          </td>
		<td class="CampoErrores" width="20px">
               
          </td>
	</tr>
	
	
	
	
	
	<tr>
     <td><?php echo$this->translate('Pais');?>:</td>
	
        <td><select id="pais" name="pais" required> 
            <option value="">Selecciona Uno...</option>
        </select>
    </td>
</tr>
<tr>

	<td><?php echo$this->translate('Estado');?>:</td>
    <td>
        <select id="estado" name="estado">
            <option value="">Selecciona Uno...</option>
        </select>
    </td>
    </tr>
    
    <tr>
    <td><?php echo$this->translate('Ciudad');?>:</td>
	<td>
      <select id="ciudad" name="idciudad" >
            <option value="">Selecciona Uno...</option>
        </select>
    </td>
    </tr>
	
	
	
</tbody></table>
  <table id="" class="ColorTable" cellpadding="3" cellspacing="3" align="center">
	<tbody><tr>
		<td class="CampoLabels">
          </td>
		<td colspan="5" class="CampoTextBox">
       <textarea name="" rows="2" cols="20" readonly="readonly" id="" style="height:150px;width:500px;text-align:left;">
EL TIEMPO DE ENTREGA ES UN ESTIMADO Y NO REPRESENTA PROMESA ALGUNA. NUESTRA EMPRESA SE COMPROMETE A HACER TODO SU MEJOR ESFUERZO EN COMPLETAR LA ENTREGA ATIEMPO. ES PROHIBIDO ENVIAR LIQUIDOS, CORROSIVOS ARMAS DE FUEGO Y MATERIAL PORNOGRAFICO. EN CASO DE PERDIDA DE LA CAJA, EL SEGURO PAGA EL 100% DEL VALOR ASEGURADO.PERDIDA PARCIAL. EL SEGURO SE PAGARA LO PROPORCIONAL AL VALOR ASEGURADO. TODA LAS CAJAS ESTAN SUJETAS A INSPECCION RASTREO DE PAQUETE:
</textarea>
          </td>
	</tr>
	<tr>
		<td>
          </td>
		<td colspan="5" class="CampoTextBox" align="center">
                <span style="display:inline-block;width:200px;">
                <input id="terminos" name="terminos" type="checkbox"><label for="">Acepto las condiciones</label></span>
          </td>
	</tr>
	<tr>
		<td class="CampoLabels">
                <span id="" class="CampoLabels" style="display:inline-block;width:120px;">Password</span>
          </td>
		<td class="CampoTextBox">
               <input name="password" maxlength="10" id="" style="width:150px;" type="password"><span id="" style="color:Red;">*</span></td>
		<td class="CampoErrores" width="20px">
               
          </td>
		<td class="CampoLabels">
                <span id="" class="CampoLabels">Repita el password</span>
          </td>
		<td class="CampoTextBox">
                <input name="password1" maxlength="10" id="" style="width:150px;" type="password"><span id="" style="color:Red;">*</span>
          </td>
		<td class="CampoErrores" width="20px">
             
          </td>
	</tr>
</tbody></table>

    <br>
    
    <table class="ColorTable" align="center">
        <tbody><tr>
            <td align="center">
                <input name="button" id="" type="submit" value="Enviar"  >
            </td>
        </tr>
 </tbody></table></form>
</div>
</div>

        </div>
    </div>
    

</div>

<!-- coloque aqui solo lo de la mitad -->



</div>
</div>
</html>